steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA", "."]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "$REPO_NAME"
      - "--image"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--add-secrets"
      - "VITE_API_URL=VITE_API_URL:latest,VITE_FRONTEND_URL=VITE_FRONTEND_URL:latest,VITE_FB_API_KEY=VITE_FB_API_KEY:latest,VITE_FB_AUTH_DOMAIN=VITE_FB_AUTH_DOMAIN:latest,VITE_PROJECT_ID=VITE_PROJECT_ID:latest,VITE_STORAGE_BUCKET=VITE_STORAGE_BUCKET:latest,VITE_MESSAGING_SENDER_ID=VITE_MESSAGING_SENDER_ID:latest,VITE_MEASUREMENT_ID=VITE_MEASUREMENT_ID:latest"

images:
  - "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
