steps:
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Debugging environment variables:"
        env

  # Debug: Try to access and print secrets
  - name: 'gcr.io/cloud-builders/gcloud'
      entrypoint: 'bash'
      args:
        - '-c'
        - |
          echo "Attempting to access secrets:"
          echo "VITE_API_URL: $$VITE_API_URL"
          echo "VITE_FRONTEND_URL: $$VITE_FRONTEND_URL"
          echo "VITE_FB_API_KEY: $$VITE_FB_API_KEY"

      secretEnv:
        - VITE_API_URL
        - VITE_FRONTEND_URL
        - VITE_FB_API_KEY


  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA",
        "--build-arg VITE_API_URL="$$VITE_API_URL",
        "--build-arg"
        "VITE_FRONTEND_URL=${_VITE_FRONTEND_URL}",
        "--build-arg",
        "VITE_FB_API_KEY=${_VITE_FB_API_KEY}",
        "--build-arg",
        "VITE_FB_AUTH_DOMAIN=${_VITE_FB_AUTH_DOMAIN}",
        "--build-arg",
        "VITE_PROJECT_ID=${_VITE_PROJECT_ID}",
        "--build-arg",
        "VITE_STORAGE_BUCKET=${_VITE_STORAGE_BUCKET}",
        "--build-arg",
        "VITE_MESSAGING_SENDER_ID=${_VITE_MESSAGING_SENDER_ID}",
        "--build-arg",
        "VITE_MEASUREMENT_ID=${_VITE_MEASUREMENT_ID}",
        ".",
      ]

    secretEnv:
      [
        "_VITE_API_URL",
        "_VITE_FRONTEND_URL",
        "_VITE_FB_API_KEY",
        "_VITE_FB_AUTH_DOMAIN",
        "_VITE_PROJECT_ID",
        "_VITE_STORAGE_BUCKET",
        "_VITE_MESSAGING_SENDER_ID",
        "_VITE_MEASUREMENT_ID",
      ]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "$REPO_NAME"
      - "--image"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"
      - "--region"
      - "us-east5"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

images:
  - "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/VITE_API_URL/versions/latest
      env: "VITE_API_URL"
    - versionName: projects/$PROJECT_ID/secrets/VITE_FRONTEND_URL/versions/latest
      env: "VITE_FRONTEND_URL"
    - versionName: projects/$PROJECT_ID/secrets/VITE_FB_API_KEY/versions/latest
      env: "VITE_FB_API_KEY"
    - versionName: projects/$PROJECT_ID/secrets/VITE_FB_AUTH_DOMAIN/versions/latest
      env: "VITE_FB_AUTH_DOMAIN"
    - versionName: projects/$PROJECT_ID/secrets/VITE_PROJECT_ID/versions/latest
      env: "VITE_PROJECT_ID"
    - versionName: projects/$PROJECT_ID/secrets/VITE_STORAGE_BUCKET/versions/latest
      env: "VITE_STORAGE_BUCKET"
    - versionName: projects/$PROJECT_ID/secrets/VITE_MESSAGING_SENDER_ID/versions/latest
      env: "VITE_MESSAGING_SENDER_ID"
    - versionName: projects/$PROJECT_ID/secrets/VITE_MEASUREMENT_ID/versions/latest
      env: "VITE_MEASUREMENT_ID"
