name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: brolympics-7368d  # Updated to match VITE_PROJECT_ID
  SERVICE_NAME: brolympics-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      env:
        VITE_API_URL: ${{ secrets.VITE_API_URL }}
        VITE_FRONTEND_URL: ${{ secrets.VITE_FRONTEND_URL }}
        VITE_FB_API_KEY: ${{ secrets.VITE_FB_API_KEY }}
        VITE_FB_AUTH_DOMAIN: ${{ secrets.VITE_FB_AUTH_DOMAIN }}
        VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID }}
        VITE_STORAGE_BUCKET: ${{ secrets.VITE_STORAGE_BUCKET }}
        VITE_MESSAGING_SENDER_ID: ${{ secrets.VITE_MESSAGING_SENDER_ID }}
        VITE_APP_ID: ${{ secrets.VITE_APP_ID }}
        VITE_MEASUREMENT_ID: ${{ secrets.VITE_MEASUREMENT_ID }}
      run: |
        docker build \
          --build-arg VITE_API_URL=$VITE_API_URL \
          --build-arg VITE_FRONTEND_URL=$VITE_FRONTEND_URL \
          --build-arg VITE_FB_API_KEY=$VITE_FB_API_KEY \
          --build-arg VITE_FB_AUTH_DOMAIN=$VITE_FB_AUTH_DOMAIN \
          --build-arg VITE_PROJECT_ID=$VITE_PROJECT_ID \
          --build-arg VITE_STORAGE_BUCKET=$VITE_STORAGE_BUCKET \
          --build-arg VITE_MESSAGING_SENDER_ID=$VITE_MESSAGING_SENDER_ID \
          --build-arg VITE_APP_ID=$VITE_APP_ID \
          --build-arg VITE_MEASUREMENT_ID=$VITE_MEASUREMENT_ID \
          -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA .
        docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
